### ISSUE TITLE
a UB sanitizer is not a series of print statements

### ISSUE THREAD

**Issue by gek169** [Abb1x/tinyubsan#3]
this "UBsan implementation" is just a series of print statements if a null/misaligned pointer is passed to a function.

This is an insult to real undefined behavior sanitizers

**Comment by Abb1x** [comment]
ok

**Comment by Abb1x** [comment]
What would be the proper term then?
UB handler?

**Comment by sleepy-monax** [comment]
Yeah that how libubsan is supposed to work

**Comment by Supercip971** [comment]
https://github.com/SerenityOS/serenity/blob/ab88f4e082ac68537ba1a634481ec531450e0e0b/Userland/Libraries/LibSanitizer/UBSanitizer.cpp serenity do the same thing btw
